In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl

In [2]:
df=pd.read_csv("Book2.csv")

In [3]:
df.head(5)

Name  HBPM  Age  BMI  Sex  Level_of_Stress  Spo2 level % (Random)  \
0     Ann   111   34   23    1                2                     95   
1     Sam    87   54   33    1                3                     92   
2    Matt   100   70   49    0                2                     92   
3    Matt    90   71   50    0                1                     97   
4  George   100   52   19    0                2                     92   

   Normal Condition  
0             False  
1             False  
2             False  
3              True  
4             False

In [4]:
df.shape

(799, 8)

In [5]:
df.isnull().sum()

Name                     0
HBPM                     0
Age                      0
BMI                      0
Sex                      0
Level_of_Stress          0
Spo2 level % (Random)    0
Normal Condition         0
dtype: int64

In [6]:
df.dtypes

Name                     object
HBPM                      int64
Age                       int64
BMI                       int64
Sex                       int64
Level_of_Stress           int64
Spo2 level % (Random)     int64
Normal Condition           bool
dtype: object

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
lb=LabelEncoder()

In [9]:
df['Normal Condition']=lb.fit_transform(df['Normal Condition'])

In [10]:
df.dtypes

Name                     object
HBPM                      int64
Age                       int64
BMI                       int64
Sex                       int64
Level_of_Stress           int64
Spo2 level % (Random)     int64
Normal Condition          int64
dtype: object

In [11]:
df.head(10)

Name  HBPM  Age  BMI  Sex  Level_of_Stress  Spo2 level % (Random)  \
0     Ann   111   34   23    1                2                     95   
1     Sam    87   54   33    1                3                     92   
2    Matt   100   70   49    0                2                     92   
3    Matt    90   71   50    0                1                     97   
4  George   100   52   19    0                2                     92   
5    Matt    75   23   48    0                3                     96   
6     ram    90   43   41    1                3                     95   
7    Matt    65   48   20    0                2                     92   
8   yugal   100   72   44    0                3                     96   
9    aman    65   40   44    0                2                     98   

   Normal Condition  
0                 0  
1                 0  
2                 0  
3                 1  
4                 0  
5                 1  
6                 1  
7                 0  
8                 1  
9                 1

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
df.tail(5)

Name  HBPM  Age  BMI  Sex  Level_of_Stress  Spo2 level % (Random)  \
794  George   107   25   15    1                1                     92   
795   rohit    99   31   25    0                1                     98   
796   rohit    72   49   18    0                1                     92   
797     Sam   111   61   29    0                1                     92   
798     ram   100   29   18    1                2                     98   

     Normal Condition  
794                 0  
795                 1  
796                 0  
797                 0  
798                 1

In [14]:
x=df[['HBPM','Spo2 level % (Random)']]

In [15]:
y=df['Normal Condition']

In [16]:
x

HBPM  Spo2 level % (Random)
0     111                     95
1      87                     92
2     100                     92
3      90                     97
4     100                     92
..    ...                    ...
794   107                     92
795    99                     98
796    72                     92
797   111                     92
798   100                     98

[799 rows x 2 columns]

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.75)

In [18]:
#from sklearn.linear_model import LinearRegression

In [19]:
#m1=LinearRegression()

In [20]:
#m1.fit(x,y)

In [21]:
#m1.score(x,y)

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
m2=LogisticRegression()

In [24]:
m2.fit(x,y)

LogisticRegression()

In [25]:
m2.score(x,y)

0.899874843554443

In [26]:
m2.predict([[75,97]])

C:\Users\ravib\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [27]:
y_pred=m2.predict(x_test)

In [28]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0], dtype=int64)

In [29]:
m2.predict([[21,34]])

C:\Users\ravib\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [30]:
m2.predict([[65,90]])

C:\Users\ravib\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [32]:
cm_rf = confusion_matrix(y_test,y_pred)
print(cm_rf)
print(classification_report(y_test,y_pred))

[[ 77  17]
 [  0 106]]
              precision    recall  f1-score   support

           0       1.00      0.82      0.90        94
           1       0.86      1.00      0.93       106

    accuracy                           0.92       200
   macro avg       0.93      0.91      0.91       200
weighted avg       0.93      0.92      0.91       200

